"""empty message

Revision ID: e03623737f74
Revises: ebe982484d0b
Create Date: 2019-01-26 15:00:39.246156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03623737f74'
down_revision = 'ebe982484d0b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.add_column('recipe', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('filename', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_recipe_category_id_category'), 'recipe', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_recipe_category_id_category'), 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'filename')
    op.drop_column('recipe', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
