"""empty message

Revision ID: ebe982484d0b
Revises: 94d44dbd3ae2
Create Date: 2019-01-26 13:23:21.811343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe982484d0b'
down_revision = '94d44dbd3ae2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_ingredient_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    # ### end Alembic commands ###
