"""empty message

Revision ID: 61b4ce279939
Revises: 3639883d8daa
Create Date: 2019-01-27 20:02:44.653957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b4ce279939'
down_revision = '3639883d8daa'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'hidden')
    # ### end Alembic commands ###
